# Generated by Django 4.2.5 on 2023-09-23 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('order_type', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Maid Request', 'Maid Request'), ('Technician Request', 'Technician Request'), ('Amenity Request', 'Amenity Request')], max_length=20)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Cancel', 'Cancel')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('defect_type', models.CharField(blank=True, max_length=50, null=True)),
                ('amenity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workorders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
