# Generated by Django 4.2.5 on 2023-09-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
